
on:
  push:
    branches:
      - main
      - dev

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout
  
env:
  AWS_BUCKET_NAME : "baseline-aws-budgets"
  AWS_REGION : "eu-west-1"
  IAM_DEPLOY_ROLE_ARN: 'arn:aws:iam::016630595874:role/GitHubActionsDeploymentRole'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: aws-actions/configure-aws-credentials@v4
      id: creds
      with:
        role-to-assume: ${{ env.IAM_DEPLOY_ROLE_ARN }}
        role-session-name: gh-deploy-session
        aws-region: ${{ env.AWS_REGION }}
        output-credentials: true
      
    - name: Copy index.html to s3
      run: "aws s3 sync *.yaml s3://${{ env.AWS_BUCKET_NAME }}/"