
on:
  push:
    branches:
      - main
      - dev

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout
  
env:
  AWS_BUCKET_NAME : "baseline-aws-budgets"
  AWS_REGION : "eu-west-1"
  IAM_DEPLOY_ROLE_ARN: 'arn:aws:iam::016630595874:role/GitHubActionsDeploymentRole'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: aws-actions/configure-aws-credentials@v4
      id: creds
      with:
        role-to-assume: ${{ env.IAM_DEPLOY_ROLE_ARN }}
        role-session-name: gh-deploy-session
        aws-region: ${{ env.AWS_REGION }}
        output-credentials: true

    # - uses: shallwefootball/s3-upload-action@master
    #   with:
    #     aws_bucket: ${{ secrets.AWS_BUCKET }}
    #     source_dir: '.'

    - uses: shallwefootball/s3-upload-action@master
      with:
        aws_key_id: ${{ steps.creds.outputs.aws-access-key-id }}
        aws_secret_access_key: ${{ steps.creds.outputs.aws-secret-access-key }}
        aws_bucket: ${{ env.AWS_BUCKET_NAME }}
        source_dir: '.'
      
    - name: Copy index.html to s3
      run: |
        aws s3 sync . s3://${{ env.AWS_BUCKET_NAME }}/