
on:
  push:
    branches:
      - main
      - dev

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: 'arn:aws:iam::016630595874:role/GitHubActionsDeploymentRole' # ${{ env.IAM_DEPLOY_ROLE_ARN }}
        role-session-name: samplerolesession
        aws-region: 'eu-west-1' # ${{ env.AWS_REGION }}
        
    - uses: hkusu/s3-upload-action@v2
      with:
        #aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        #aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: 'eu-west-1' # ${{ secrets.AWS_REGION  || 'eu-west-1' }}
        aws-bucket: 'baseline-aws-budgets' # ${{ secrets.AWS_BUCKET_NAME || 'baseline-aws-budgets' }}
        file-path: './*.yaml'
